site_name: Arkade 5 - Arkivverket

pages:
- Hjem: 'index.md'
- Installasjonsveiledning: 'installasjonsveiledning.md'
- Brukerveiledning: 'brukerveiledning.md'
- 'Systemdokumentasjon':
    - 'Overview': 'system-overview.md' 
- Versjonshistorikk: 'versjonshistorikk.md'